name: Build Android APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Inject Environment Variables
        run: |
          cat <<EOF > lib/env.dart
          class Env {
            static const String supabaseUrl = '${{ secrets.SUPABASE_URL }}';
            static const String supabaseAnonKey = '${{ secrets.SUPABASE_ANON_KEY }}';
            static const String bmoniBaseUrl = 'https://embedded-dev.bmoni.com/v1';
            static const String bmoniApiKey = '${{ secrets.BMONI_API_KEY }}';
          }
          EOF

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release --android-skip-build-dependency-validation

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
